#!/bin/bash
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-01;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-02;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-03;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-04;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-05;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-06;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-07;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-08;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-09;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-10;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-11;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-12;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-13;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-14;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-15;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-16;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-17;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-18;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-19;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-20;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-21;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-22;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-23;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-24;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-25;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-26;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-27;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-28;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-29;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-30;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-31;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-32;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-33;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-34;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-35;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-36;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-37;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-38;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-30-ensemble/eOR1-IA-FLX-30-ensemble-39;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
