#!/bin/bash
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-01;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-02;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-03;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-04;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-05;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-06;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-07;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-08;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-09;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-10;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-11;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-12;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-13;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-14;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-15;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-16;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-17;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-18;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-19;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-20;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-21;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-22;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-23;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-24;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-25;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-26;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-27;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-28;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-29;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-30;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-31;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-32;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-33;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-34;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-35;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-36;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-37;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-38;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-39;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-40;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-41;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-42;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-43;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-44;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-45;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-46;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-47;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-48;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-49;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-50;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-51;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-52;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-53;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-54;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-55;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-56;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-57;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-58;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-59;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-60;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
cd eOR1-IA-FLX-29-ensemble/eOR1-IA-FLX-29-ensemble-61;
/ccc/work/cont003/gen1140/liufangy/NEMOGCM_For_SETE/modipsl/libIGCM/clean_latestPackperiod.job; cd -;
